spring:
  application:
    name: skillbox-jwt
  data:
    redis:
      host: localhost
      port: 6379


  datasource:
    url: jdbc:postgresql://localhost:5557/skillbox
    username: spring_user
    password: spring_pass
    driverClassName: org.postgresql.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
  app:
    jwt:
      secret: "skillbox_jwt_secret"
      tokenExpiratiom: 3m
      refreshTokenExpiratiom: 30m
#      token: "skillbox_jwt_token"